### ISSUE TITLE
`bazel-toolchain` does not support `NixOS`

### ISSUE THREAD

**Issue by rroohhh** [aarnphm/whispercpp#45]
`bazel-toolchain`, which was added in bdd5302003ce8c5a957337e4c4a05566466b14b1 does not support `NixOS` (see https://github.com/grailbio/bazel-toolchain/issues/58), making (dev) installation on `NixOS` impossible currently.

**Comment by aarnphm** [comment]
I'm ok with removing this right now. Maybe we don't even need clang. 🤔

**Comment by aarnphm** [comment]
I have remove llvm toolchain on main. Sorry for the breakage.
