### ISSUE TITLE
bug:  Readme issues

### ISSUE THREAD

**Issue by sorgfresser** [aarnphm/whispercpp#82]
### Describe the bug

I detected multiple README flaws. 

1. It should be `w.transcribe(np.ones(16000))` with just one dimension, at least that's what worked for me (and the example afterwards uses `flatten()`, so it is done here.
2. Might be mistaken on this one, but 

> Running transcription on a given Numpy array. This calls full from whisper.cpp. If num_proc is greater than 1, it will use full_parallel instead.

Is simply not the case. In the code in `__init__.py`, `transcribe` always calls `full_parallel`

### To reproduce

Copy paste example README.md code. It fails.

### Expected behavior

It doesn't fail.

### Environment

python: 3.9
plattform: Ubuntu 20.04

**Comment by aarnphm** [comment]
full_parallel calls full if num_proc=1

**Comment by sorgfresser** [comment]
Okay, so 2. is out of the way. What about 1. though? I still get the error if I use `(1, 16000)` and `16000` works.
